openapi: 3.0.0
info:
  title: Planinha
  description: API do Planinha.
  version: 1.0.0
servers:
- url: http://localhost:8080/planinha/
  description: localhost
- url: http://planinha.herokuapp.com/v1.0
  description: herokuapp
- url: https://virtserver.swaggerhub.com/brunoabdon/planinha/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- accessCode:
  - read
  - write
paths:
  /contas:
    get:
      summary: Lista as contas
      description: Lista as contas existentes.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayDeConta'
    post:
      summary: Cria uma conta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContaExistente'
        required: true
      responses:
        204:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
  /contas/{id}:
    get:
      summary: Recupera uma Conta
      description: Recupera uma Conta.
      parameters:
      - name: id
        in: path
        description: o id da Conta.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Id'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
        404:
          description: A conta não exsite.
    post:
      summary: Altera o nome de uma conta
      parameters:
      - name: id
        in: path
        description: o id da Conta.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContaExistente'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
    delete:
      summary: Deleta uma conta.
      parameters:
      - name: id
        in: path
        description: o id da Conta.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Id'
      responses:
        204:
          description: Deletado
        404:
          description: A conta não exsite.
components:
  schemas:
    Id:
      minimum: 0
      type: integer
      format: int64
    Conta:
      required:
      - id
      - nome
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
    ArrayDeConta:
      type: array
      items:
        $ref: '#/components/schemas/Conta'
    ContaExistente:
      required:
      - nome
      type: object
      properties:
        nome:
          type: string
