openapi: 3.0.0
info:
  title: Planinha
  description: API do Planinha.
  version: 1.0.0
servers:
- url: http://localhost:8080/planinha/
  description: localhost
- url: http://planinha.herokuapp.com/v1.0
  description: herokuapp
security:
- accessCode:
  - read
  - write
paths:
  /contas:
    get:
      summary: Lista as contas existentes.
      tags:
        - Conta
      responses:
        200:
          description: As contas foram listadas com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Conta"
    post:
      summary: Cria uma conta.
      tags:
        - Conta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchConta'
        required: true
      responses:
        204:
          description: A conta foi criada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
  /contas/{conta_id}:
    parameters:
    - name: conta_id
      in: path
      description: O id da Conta.
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    get:
      summary: Recupera uma Conta.
      tags:
        - Conta
      responses:
        200:
          description: A conta foi recuperada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
        404:
          description: A conta não exsite.
    put:
      summary: Altera o nome de uma conta.
      tags:
        - Conta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchConta'
        required: true
      responses:
        200:
          description: A conta foi alterada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conta'
        404:
          description: A conta nem existe.
    delete:
      summary: Deleta uma conta.
      tags:
        - Conta
      responses:
        204:
          description: A conta foi deletada com sucesso.
        404:
          description: A conta nem existe.
        409:
           description: |
            Existem operações referenciando esta conta e ela não pode ser 
            deletada.
  /contas/{conta_id}/extratos:
    parameters:
    - name: conta_id
      in: path
      description: O id da conta de que se quer os extratos.
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    get:
      summary: Retorna os extratos de uma conta.
      tags:
        - Extrato
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExtratoResumido'
        404:
          description: A conta nem existe.
  /contas/{conta_id}/extratos/{extrato_id}:
    parameters:
    - name: conta_id
      in: path
      description: O id da conta de que se quer o extrato.
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    get:
      summary: Retorna um extrato específico.
      tags:
        - Extrato
      parameters:
      - name: extrato_id
        in: path
        description: O id do extrato.
        required: true
        schema:
          type: string
      responses:
        200:
          description: O extrato foi recuperado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Extrato'
        404:
          description: O extrato (ou a conta) nem existe.
  /operacoes/:
    get:
      summary: Lista operações, de acordo com as restrições específicadas.
      tags:
        - Operação
      parameters:
      - name: mes
        in: query
        description: |
          Mês e ano, no formato MM-YYYY, em que as operações aconteceram.

          É equivalente a passar o parâmetro dataMinima com o primeiro dia desse mês e dataMaxima com o último.
        required: false
        schema:
          type: string
      - name: dataMinima
        in: query
        description: |
          A data limite mínima das operações a serem listadas. Operações que 
          aconteceram antes dessa data não serão listadas.
        required: false
        schema:
          type: string
          format: date
      - name: dataMaxima
        in: query
        description: |
          A data limite máxima das operações a serem listadas. Operações que 
          aconteceram depois dessa data não serão listadas.
        required: false
        schema:
          type: string
          format: date
      responses:
        200:
          description: As operações foram consultadas com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Operacao'
    post:
      summary: Cria uma operação.
      tags:
        - Operação
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchOperacao'
        required: true
      responses:
        201:
          description: A operação foi criada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operacao'
  /operacoes/{operacao_id}:
    parameters:
      - name: operacao_id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/Id'
    get:
      summary: Recupera uma operação.
      tags:
        - Operação
      responses:
        200:
          description: A operação foi recuperada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Operacao'
        404:
          description: A operação não existe.
    delete:
      summary: Deleta uma operação.
      tags:
        - Operação
      responses:
        204:
          description: A operação foi deletada com sucesso.
        404:
          description: Essa operação nem existe.
  /operacoes/{operacao_id}/fato:
    parameters:
    - name: operacao_id
      in: path
      description: O id da operação.
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    get:
      summary: Recupera o fato de um operção.
      tags:
        - Fato
      responses:
        200:
          description: O fato foi recuperado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fato'
        404:
          description: A operação nem existe.
    put:
      summary: Altera um fato.
      tags:
        - Fato
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchFato'
        required: true
      responses:
        200:
          description: O fato foi alterado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fato'
        404:
          description: A operação nem existe.
  /operacoes/{operacao_id}/movimentacoes:
    parameters:
    - name: operacao_id
      in: path
      description: A operação da qual as movimentações fazem parte.
      required: true
      schema:
        $ref: "#/components/schemas/Id"
    get:
      summary: Lista as movimentações de uma dada operação.
      tags:
        - Movimentação
      responses:
        200:
          description: |
            A lista, possivelmente vazia, foi recuperada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movimentacao'
        404:
          description: A operação nem existe.
    post:
      summary: Cria uma nova movimentação numa operação.
      tags:
        - Movimentação
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Movimentacao"
      responses:
        201:
          description: A movimentação foi criada com sucesso.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movimentacao"
        404:
          description: A operação nem existe.
        409:
          description: |
            A movimentação não pode ser criada por que já existe uma 
            movimentação para esta conta nesta operação.
  /operacoes/{operacao_id}/movimentacoes/{conta_id}:
    parameters:
    - name: operacao_id
      in: path
      description: A operação da qual as movimentações fazem parte.
      required: true
      schema:
        $ref: "#/components/schemas/Id"
    - name: conta_id
      in: path
      description: A conta à qual esta movimentação diz respeito.
      required: true
      schema:
        $ref: "#/components/schemas/Id"
    get:
      summary: Recupera uma movimentação específica.
      tags:
        - Movimentação
      responses:
        200:
          description: |
            A movimentaçao foi recuperada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movimentacao'
        404:
          description: |
            A operação nem existe, ou não existem uma movimentação pra esa 
            conta nesta operação.
    put:
      summary: Atualiza o valor de uma movimentação.
      tags:
        - Movimentação
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchMovimentacao'
      responses:
        200:
          description: A movimentação foi atualizada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movimentacao'
        404:
          description: |
            A operação nem existe, ou não existem uma movimentação pra esa 
            conta nesta operação.
    delete:
      summary: Deleta uma movimentação de uma operação.       
      tags: 
        - Movimentação
      responses:
        204:
          description: A movimentação foi deletada com sucesso.
        403:
          description: |
            A movimentação não pode ser deletada por que ela é a única restante
            na operação. Uma operação não pode existir sem movimentações.
        404:
          description: |
            A operação nem existe, ou não existem uma movimentação pra esa 
            conta nesta operação.
components:
  schemas:
    Id:
      $ref: "types.yaml#/Id"
    Conta:
      $ref: "conta.yaml#/Conta"
    Fato:
      $ref: "fato.yaml#/Fato"
    Extrato:
      $ref: "extrato.yaml#/Extrato"
    ExtratoResumido:
      $ref: "extrato.yaml#/ExtratoResumido"
    Movimentacao:
      $ref: "movimentacao.yaml#/Movimentacao"
    Operacao:
      $ref: "operacao.yaml#/Operacao"
    PatchConta:
      $ref: "conta.yaml#/PatchConta"
    PatchFato:
      $ref: "fato.yaml#/PatchFato"
    PatchMovimentacao:
      $ref: "movimentacao.yaml#/PatchMovimentacao"
    PatchOperacao:
      $ref: "operacao.yaml#/PatchOperacao"