spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planinhadb
    username: planinha
    password: ${DB_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
    name: 'planinha@postgresql'

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:    
        #'[show_sql]': true
        '[use_sql_comments]': true
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    
server:
  port: 8080
  servlet:
    context-path: /planinha
    
logging:
  level:
    ROOT: INFO
    '[com.github.brunoabdon]': TRACE
    '[org.hibernate.SQL]': WARN #ERROR
    '[org.hibernate.type.descriptor.sql.BasicBinder]': WARN #TRACE
    '[org.springframework.jdbc.core.JdbcTemplate]': WARN #DEBUG
    '[org.springframework.jdbc.core.StatementCreatorUtils]': TRACE
